type VisualType = "tube" | "tire" | "brakes" | "controller" | "controller48" | "charger" | "throttle" | "display";

export function ProductVisual({ type }: { type: VisualType }) {
  if (type === "tube" || type === "tire") return <div className={`relative size-24 rounded-full border-[15px] ${type === "tire" ? "border-slate-950" : "border-slate-700"} bg-slate-400 shadow-lg`}><div className="absolute inset-2 rounded-full border-2 border-slate-600 bg-[#f1f7fa]" /><span className="absolute inset-[-11px] rounded-full border border-slate-500/30" /></div>;
  if (type === "brakes") return <div className="relative flex w-28 items-center justify-center gap-2"><div className="h-16 w-9 rotate-[-15deg] rounded-md border-2 border-slate-700 bg-slate-800 shadow" /><div className="h-16 w-9 rotate-[15deg] rounded-md border-2 border-slate-700 bg-slate-800 shadow" /><span className="absolute bottom-2 h-3 w-20 rounded bg-[#c18149]" /></div>;
  if (type === "controller" || type === "controller48") return <div className={`relative h-20 w-28 rounded-lg border-2 ${type === "controller48" ? "border-[#144e70] bg-[#1d6c96]" : "border-slate-500 bg-slate-700"} shadow-lg`}><span className="absolute inset-x-4 top-4 h-1 rounded bg-white/50" /><span className="absolute inset-x-4 top-8 h-1 rounded bg-white/30" /><span className="absolute -left-7 top-7 h-6 w-7 rounded-l bg-slate-800" /><span className="absolute -right-7 top-7 h-6 w-7 rounded-r bg-slate-800" /></div>;
  if (type === "charger") return <div className="relative h-20 w-28 rounded-xl bg-slate-950 shadow-lg"><span className="absolute left-5 top-5 h-6 w-12 rounded bg-[#45bc76]" /><span className="absolute -right-9 top-8 h-1 w-9 bg-slate-700" /><span className="absolute -right-11 top-7 h-3 w-3 rounded-r bg-slate-700" /></div>;
  if (type === "throttle") return <div className="relative h-20 w-24"><span className="absolute left-8 top-2 h-16 w-9 rounded-t-[2rem] rounded-b-md bg-slate-800 shadow-lg" /><span className="absolute left-1 top-9 h-3 w-14 rounded-full bg-slate-950" /><span className="absolute right-2 top-5 size-3 rounded-full bg-[#0b85c6]" /></div>;
  return <div className="relative h-20 w-28 rounded-xl border-[5px] border-slate-800 bg-slate-950 shadow-lg"><div className="absolute inset-2 rounded bg-[#43b8d0]"><span className="absolute left-2 top-2 h-5 w-7 rounded bg-white/80" /><span className="absolute bottom-2 left-2 h-1 w-12 bg-white/70" /></div></div>;
}
